# Use the latest MinIO image
FROM minio/minio:latest

# Set environment variables
ENV MINIO_ROOT_USER=minioadmin
ENV MINIO_ROOT_PASSWORD=minioadmin

# Create the data directory
RUN mkdir -p /data && \
    chmod -R 777 /data

# Expose API (9000) and Console (9090) ports
EXPOSE 9000
EXPOSE 9090

# Start MinIO server pointing to /data with the console on 9090
CMD ["server", "/data", "--console-address", ":9090"]